### ISSUE TITLE
Incompatibility With Effortless Structure Mods

### ISSUE THREAD

**Issue by dartokloning** [ludwici/CarpetVariants#1]
Good mod but make me crash when I want to use Effortless Structure, but it's OK to use Effortless Structure when carpet is not around.

I hope you can fix it and thank you for the mod.

```-- Head --
Thread: Render thread
Suspected Mods: 
	Effortless Structure (effortless), Version: 3.0.0-beta.2
		Issue tracker URL: https://github.com/huskcasaca/effortless/issues
		at TRANSFORMER/effortless@3.0.0-beta.2/dev.huskuraft.effortless.forge.core.MinecraftBlockState.canBeReplaced(MinecraftBlockState.java:117)

	Carpet Variants (carpetvariants), Version: 1.20.1-1.0.1
		at TRANSFORMER/carpetvariants@1.20.1-1.0.1/com.ludwici.carpetvariants.block.CarpetVariantBlock.m_6864_(CarpetVariantBlock.java:135)
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23270!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.ludwici.carpetvariants.block.CarpetVariantBlock.m_6864_(CarpetVariantBlock.java:135) ~[carpetvariants-1.20.1-1.0.1.jar%23178!/:1.20.1-1.0.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60629_(BlockBehaviour.java:802) ~[client-1.20.1-20230612.114412-srg.jar%23270!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:lithium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.AbstractBlockStateMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:vmp.mixins.json:general.cache_ops.fluid_state.MixinAbstractBlockAbstractBlockState,pl:mixin:A}
	at dev.huskuraft.effortless.forge.core.MinecraftBlockState.canBeReplaced(MinecraftBlockState.java:117) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.building.structure.builder.standard.Single.traceSingle(Single.java:35) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.building.structure.builder.standard.Single.traceSingle(Single.java:19) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.building.structure.builder.standard.Wall.trace(Wall.java:102) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.building.structure.builder.BlockStructure.trace(BlockStructure.java:150) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.building.Context.trace(Context.java:257) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.EffortlessClientStructureBuilder.getContextTraced(EffortlessClientStructureBuilder.java:266) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.EffortlessClientStructureBuilder.onClientTick(EffortlessClientStructureBuilder.java:573) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?] {re:mixin}
	at dev.huskuraft.effortless.api.events.EventFactory.invokeMethod(EventFactory.java:33) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.api.events.EventFactory$1.handleInvocation(EventFactory.java:42) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.api.events.EventFactory$AbstractInvocationHandler.invoke(EventFactory.java:222) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at jdk.proxy3.$Proxy98.onClientTick(Unknown Source) ~[?:?] {}
	at dev.huskuraft.effortless.forge.events.ForgeClientEventRegistry.onClientTick(ForgeClientEventRegistry.java:61) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading}
	at dev.huskuraft.effortless.forge.events.__ForgeClientEventRegistry_onClientTick_ClientTickEvent.invoke(.dynamic) ~[effortless-1.20.1-3.0.0-beta.2.jar%23197!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:935) ~[forge-1.20.1-47.2.32-universal.jar%23275!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:lithium.mixins.json:collections.mob_spawning.ForgeEventFactoryMixin,pl:mixin:A}```

**Comment by ludwici** [comment]
Hello, @dartokloning 
Thanks for the report. Could you provide some more information? I'm not particularly familiar with this mod. I'm interested in the build mode settings you tried so I can accurately reproduce the problem
