### ISSUE TITLE
Carpetscore is Required but not given? Fabric 1.21.1 and 0.16.9

### ISSUE THREAD

**Issue by suerion** [ludwici/CarpetVariants#3]
Hey, had updated Carpet Variants on fabric, but Carpetscore is not given yet?

Should it be Embed? or something?

```
[11:17:56] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[11:17:56] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:17:56] [ForkJoinPool-1-worker-5/WARN]: Mod betterallay uses the version [FABRIC]-1.4.0-1.21.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '[FABRIC]'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-2/WARN]: Mod mr_dungeons uses the version 1.9.0b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-4/WARN]: Mod mr_nice_mobsremastered uses the version 2.5b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-9/WARN]: The mod "mushrooomsmod" contains invalid entries in its mod json:
- Unsupported root entry "license link" at line 16 column 17
[11:17:56] [ForkJoinPool-1-worker-10/WARN]: Mod oceansdelight uses the version fdrf-fabric-1.0.2-1.21 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fdrf'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-4/WARN]: Mod plushified uses the version 0.8.0B which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0B'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-15/WARN]: Mod mr_scorched uses the version 1.1.4a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '4a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [ForkJoinPool-1-worker-12/WARN]: Mod waterframes uses the version 2.1.7b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:17:56] [main/WARN]: Mod resolution failed
[11:17:56] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE carpetvariants 1.21.1-1.1.0 {depends carpetscore @ [>=1.0.0]}, ROOT_FORCELOAD_SINGLE carpetvariants 1.21.1-1.1.0]
[11:17:56] [main/INFO]: Reason: [HARD_DEP carpetvariants 1.21.1-1.1.0 {depends carpetscore @ [>=1.0.0]}, HARD_DEP c2me-opts-natives-math 0.3.0+alpha.0.295+1.21.1 {depends java @ [>=22]}]
[11:17:56] [main/INFO]: SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, c2me-client-uncapvd, fabric-keybindings-v0, modmenu, roughlyenoughprofessions, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, modmenu-badges-lib, fabric-sound-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1]
[11:17:56] [main/INFO]: Fix: add [add:carpetscore 1.0.0 ([[1.0.0,∞)])], remove [], replace []
[11:17:56] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install carpetscore, version 1.0.0 or later.
More details:
	 - Mod 'Carpet Variants' (carpetvariants) 1.21.1-1.1.0 requires version 1.0.0 or later of carpetscore, which is missing!
	 - Mod 'Concurrent Chunk Management Engine (Optimizations/Natives Math)' (c2me-opts-natives-math) 0.3.0+alpha.0.295+1.21.1 requires version 22 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]

```

**Comment by suerion** [comment]
Had build it for me, from the source to test. if there is some issues, will bring an issue direct to the lib

**Comment by ludwici** [comment]
@suerion 1.21.1 version [here](https://www.curseforge.com/minecraft/mc-mods/carpets-core/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4)
I am gradually moving the core logic to a separate library to make my work easier in the future. And I always publish CarpetsCore first, and only then update CarpetVariants

**Comment by suerion** [comment]
Huh, had looked for your lib on curseforge and on modrinth, it has not appeared on both sites... this is weired okey thanks, then i need not anymore to use the own build file
